#!/bin/sh
#
# @name Canard DIAM
#
# @type Standard Plane
# @class Plane
#
# @output MAIN1 aileron
# @output MAIN2 aileron
# @output MAIN3 elevator
# @output MAIN4 payload
# @output MAIN5 throttle
# @output MAIN6 parachute
# @output MAIN7 buffer
# @output MAIN8 parachute_release
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer null <null@diam.com>
#

sh /etc/init.d/rc.fw_defaults

if [ $AUTOCNF = yes ]
then
	param set FW_AIRSPD_MIN 10
	param set FW_AIRSPD_TRIM 15
	param set FW_AIRSPD_MAX 20

	param set FW_MAN_P_MAX 55
	param set FW_MAN_R_MAX 55
	param set FW_R_LIM 55

	param set FW_WR_FF 0.2
	param set FW_WR_I 0.2
	param set FW_WR_IMAX 0.8
	param set FW_WR_P 1
	param set FW_W_RMAX 0

	# set disarmed value for the ESC
	param set PWM_DISARMED 1000
fi

set MIXER Canard

# use PWM parameters for throttle channel
set PWM_OUT 4
